/*
 Navicat Premium Data Transfer

 Source Server         : 本机MySQL
 Source Server Type    : MySQL
 Source Server Version : 50728
 Source Host           : 127.0.0.1:3306
 Source Schema         : nacos_config

 Target Server Type    : MySQL
 Target Server Version : 50728
 File Encoding         : 65001

 Date: 27/12/2019 17:37:22
*/

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- ----------------------------
-- Table structure for config_info
-- ----------------------------
DROP TABLE IF EXISTS `config_info`;
CREATE TABLE `config_info`  (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'id',
  `data_id` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT 'data_id',
  `group_id` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL,
  `content` longtext CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT 'content',
  `md5` varchar(32) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT 'md5',
  `gmt_create` datetime(0) NOT NULL DEFAULT '2010-05-05 00:00:00' COMMENT '创建时间',
  `gmt_modified` datetime(0) NOT NULL DEFAULT '2010-05-05 00:00:00' COMMENT '修改时间',
  `src_user` text CHARACTER SET utf8 COLLATE utf8_bin NULL COMMENT 'source user',
  `src_ip` varchar(20) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT 'source ip',
  `app_name` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL,
  `tenant_id` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT '' COMMENT '租户字段',
  `c_desc` varchar(256) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL,
  `c_use` varchar(64) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL,
  `effect` varchar(64) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL,
  `type` varchar(64) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL,
  `c_schema` text CHARACTER SET utf8 COLLATE utf8_bin NULL,
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE INDEX `uk_configinfo_datagrouptenant`(`data_id`, `group_id`, `tenant_id`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 38 CHARACTER SET = utf8 COLLATE = utf8_bin COMMENT = 'config_info' ROW_FORMAT = Dynamic;

-- ----------------------------
-- Records of config_info
-- ----------------------------
INSERT INTO `config_info` VALUES (1, 'provider.yaml', 'DEFAULT_GROUP', 'spring:\r\n  datasource:\r\n    username: root\r\n    password: 123456\r\n    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=UTF-8&useSSL=false\r\n    driver-class-name: com.mysql.jdbc.Driver\r\n    type: com.alibaba.druid.pool.DruidDataSource\r\n    druid:\r\n      initial-size: 5       \r\n      min-idle: 5           \r\n      max-active: 20        \r\n      test-on-borrow: true  \r\n      max-wait: 1000        \r\n  \r\n      stat-view-servlet:\r\n        enabled: true\r\n        url-pattern: /druid/*\r\n        login-username: root\r\n        login-password: 123456\r\n      filter:              \r\n        stat:\r\n          log-slow-sql: true\r\n          slow-sql-millis: 1000\r\n          merge-sql: true\r\n        wall:\r\n          config:\r\n            multi-statement-allow: true\r\n  redis:\r\n    host: 127.0.0.1\r\n    port: 6380\r\n    jedis:\r\n      pool:\r\n        max-active: 20\r\n        min-idle: 5\r\n    database: 1\r\n\r\nuseLocalCache: true', 'da92b01f9abf83dcd453d445a807be03', '2019-12-25 11:28:39', '2019-12-26 18:56:25', NULL, '127.0.0.1', '', '', 'null', 'null', 'null', 'yaml', 'null');
INSERT INTO `config_info` VALUES (30, 'provider.yaml', 'PROVIDER_GROUP', 'spring:\r\n  datasource:\r\n    username: root\r\n    password: 123456\r\n    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=UTF-8&useSSL=false\r\n    driver-class-name: com.mysql.jdbc.Driver\r\n    type: com.alibaba.druid.pool.DruidDataSource\r\n    druid:\r\n      initial-size: 5       \r\n      min-idle: 5           \r\n      max-active: 20        \r\n      test-on-borrow: true  \r\n      max-wait: 1000        \r\n  \r\n      stat-view-servlet:\r\n        enabled: true\r\n        url-pattern: /druid/*\r\n        login-username: root\r\n        login-password: 123456\r\n      filter:              \r\n        stat:\r\n          log-slow-sql: true\r\n          slow-sql-millis: 1000\r\n          merge-sql: true\r\n        wall:\r\n          config:\r\n            multi-statement-allow: true\r\n  redis:\r\n    host: 127.0.0.1\r\n    port: 6380\r\n    jedis:\r\n      pool:\r\n        max-active: 20\r\n        min-idle: 5\r\n    database: 1', '96362644a23867f4e7bc4e6cecda01e0', '2019-12-26 19:48:30', '2019-12-27 09:13:00', NULL, '127.0.0.1', '', '2572cfa6-38d4-4a72-812b-3347fe50aa98', 'provider项目使用', 'null', 'null', 'yaml', 'null');
INSERT INTO `config_info` VALUES (31, 'provider.yaml', 'PROVIDER_GROUP', 'spring:\r\n  datasource:\r\n    username: root\r\n    password: 123456\r\n    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=UTF-8&useSSL=false\r\n    driver-class-name: com.mysql.jdbc.Driver\r\n    type: com.alibaba.druid.pool.DruidDataSource\r\n    druid:\r\n      initial-size: 5       \r\n      min-idle: 5           \r\n      max-active: 20        \r\n      test-on-borrow: true  \r\n      max-wait: 1000        \r\n  \r\n      stat-view-servlet:\r\n        enabled: true\r\n        url-pattern: /druid/*\r\n        login-username: root\r\n        login-password: 123456\r\n      filter:              \r\n        stat:\r\n          log-slow-sql: true\r\n          slow-sql-millis: 1000\r\n          merge-sql: true\r\n        wall:\r\n          config:\r\n            multi-statement-allow: true\r\n  redis:\r\n    host: 127.0.0.1\r\n    port: 6380\r\n    jedis:\r\n      pool:\r\n        max-active: 20\r\n        min-idle: 5\r\n    database: 1\r\n', 'ac4d5463e4b7f0b323a59339ddeada1a', '2019-12-26 19:50:04', '2019-12-27 09:14:03', NULL, '127.0.0.1', '', '2d5193c9-4b61-453e-8eae-e0fae3b516e1', 'null', 'null', 'null', 'yaml', 'null');
INSERT INTO `config_info` VALUES (32, 'consumer.yaml', 'CONSUMER_GROUP', 'PROVIDER_GROUP: true', 'de2ab4aa468ead3cf104f711e74428bd', '2019-12-26 19:51:18', '2019-12-26 19:51:18', NULL, '127.0.0.1', '', '2572cfa6-38d4-4a72-812b-3347fe50aa98', 'consumer 项目', NULL, NULL, 'yaml', NULL);

-- ----------------------------
-- Table structure for config_info_aggr
-- ----------------------------
DROP TABLE IF EXISTS `config_info_aggr`;
CREATE TABLE `config_info_aggr`  (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'id',
  `data_id` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT 'data_id',
  `group_id` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT 'group_id',
  `datum_id` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT 'datum_id',
  `content` longtext CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT '内容',
  `gmt_modified` datetime(0) NOT NULL COMMENT '修改时间',
  `app_name` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL,
  `tenant_id` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT '' COMMENT '租户字段',
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE INDEX `uk_configinfoaggr_datagrouptenantdatum`(`data_id`, `group_id`, `tenant_id`, `datum_id`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 1 CHARACTER SET = utf8 COLLATE = utf8_bin COMMENT = '增加租户字段' ROW_FORMAT = Dynamic;

-- ----------------------------
-- Table structure for config_info_beta
-- ----------------------------
DROP TABLE IF EXISTS `config_info_beta`;
CREATE TABLE `config_info_beta`  (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'id',
  `data_id` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT 'data_id',
  `group_id` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT 'group_id',
  `app_name` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT 'app_name',
  `content` longtext CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT 'content',
  `beta_ips` varchar(1024) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT 'betaIps',
  `md5` varchar(32) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT 'md5',
  `gmt_create` datetime(0) NOT NULL DEFAULT '2010-05-05 00:00:00' COMMENT '创建时间',
  `gmt_modified` datetime(0) NOT NULL DEFAULT '2010-05-05 00:00:00' COMMENT '修改时间',
  `src_user` text CHARACTER SET utf8 COLLATE utf8_bin NULL COMMENT 'source user',
  `src_ip` varchar(20) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT 'source ip',
  `tenant_id` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT '' COMMENT '租户字段',
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE INDEX `uk_configinfobeta_datagrouptenant`(`data_id`, `group_id`, `tenant_id`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 1 CHARACTER SET = utf8 COLLATE = utf8_bin COMMENT = 'config_info_beta' ROW_FORMAT = Dynamic;

-- ----------------------------
-- Table structure for config_info_tag
-- ----------------------------
DROP TABLE IF EXISTS `config_info_tag`;
CREATE TABLE `config_info_tag`  (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'id',
  `data_id` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT 'data_id',
  `group_id` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT 'group_id',
  `tenant_id` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT '' COMMENT 'tenant_id',
  `tag_id` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT 'tag_id',
  `app_name` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT 'app_name',
  `content` longtext CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT 'content',
  `md5` varchar(32) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT 'md5',
  `gmt_create` datetime(0) NOT NULL DEFAULT '2010-05-05 00:00:00' COMMENT '创建时间',
  `gmt_modified` datetime(0) NOT NULL DEFAULT '2010-05-05 00:00:00' COMMENT '修改时间',
  `src_user` text CHARACTER SET utf8 COLLATE utf8_bin NULL COMMENT 'source user',
  `src_ip` varchar(20) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT 'source ip',
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE INDEX `uk_configinfotag_datagrouptenanttag`(`data_id`, `group_id`, `tenant_id`, `tag_id`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 1 CHARACTER SET = utf8 COLLATE = utf8_bin COMMENT = 'config_info_tag' ROW_FORMAT = Dynamic;

-- ----------------------------
-- Table structure for config_tags_relation
-- ----------------------------
DROP TABLE IF EXISTS `config_tags_relation`;
CREATE TABLE `config_tags_relation`  (
  `id` bigint(20) NOT NULL COMMENT 'id',
  `tag_name` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT 'tag_name',
  `tag_type` varchar(64) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT 'tag_type',
  `data_id` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT 'data_id',
  `group_id` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT 'group_id',
  `tenant_id` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT '' COMMENT 'tenant_id',
  `nid` bigint(20) NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`nid`) USING BTREE,
  UNIQUE INDEX `uk_configtagrelation_configidtag`(`id`, `tag_name`, `tag_type`) USING BTREE,
  INDEX `idx_tenant_id`(`tenant_id`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 1 CHARACTER SET = utf8 COLLATE = utf8_bin COMMENT = 'config_tag_relation' ROW_FORMAT = Dynamic;

-- ----------------------------
-- Table structure for group_capacity
-- ----------------------------
DROP TABLE IF EXISTS `group_capacity`;
CREATE TABLE `group_capacity`  (
  `id` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `group_id` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL DEFAULT '' COMMENT 'Group ID，空字符表示整个集群',
  `quota` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '配额，0表示使用默认值',
  `usage` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '使用量',
  `max_size` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '单个配置大小上限，单位为字节，0表示使用默认值',
  `max_aggr_count` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '聚合子配置最大个数，，0表示使用默认值',
  `max_aggr_size` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '单个聚合数据的子配置大小上限，单位为字节，0表示使用默认值',
  `max_history_count` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '最大变更历史数量',
  `gmt_create` datetime(0) NOT NULL DEFAULT '2010-05-05 00:00:00' COMMENT '创建时间',
  `gmt_modified` datetime(0) NOT NULL DEFAULT '2010-05-05 00:00:00' COMMENT '修改时间',
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE INDEX `uk_group_id`(`group_id`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 1 CHARACTER SET = utf8 COLLATE = utf8_bin COMMENT = '集群、各Group容量信息表' ROW_FORMAT = Dynamic;

-- ----------------------------
-- Table structure for his_config_info
-- ----------------------------
DROP TABLE IF EXISTS `his_config_info`;
CREATE TABLE `his_config_info`  (
  `id` bigint(64) UNSIGNED NOT NULL,
  `nid` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `data_id` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `group_id` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `app_name` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT 'app_name',
  `content` longtext CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `md5` varchar(32) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL,
  `gmt_create` datetime(0) NOT NULL DEFAULT '2010-05-05 00:00:00',
  `gmt_modified` datetime(0) NOT NULL DEFAULT '2010-05-05 00:00:00',
  `src_user` text CHARACTER SET utf8 COLLATE utf8_bin NULL,
  `src_ip` varchar(20) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL,
  `op_type` char(10) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL,
  `tenant_id` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT '' COMMENT '租户字段',
  PRIMARY KEY (`nid`) USING BTREE,
  INDEX `idx_gmt_create`(`gmt_create`) USING BTREE,
  INDEX `idx_gmt_modified`(`gmt_modified`) USING BTREE,
  INDEX `idx_did`(`data_id`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 39 CHARACTER SET = utf8 COLLATE = utf8_bin COMMENT = '多租户改造' ROW_FORMAT = Dynamic;

-- ----------------------------
-- Records of his_config_info
-- ----------------------------
INSERT INTO `his_config_info` VALUES (0, 1, 'provider.yaml', 'DEFAULT_GROUP', '', 'spring:\r\n  datasource:\r\n    username: root\r\n    password: 123456\r\n    url: jdbc:mysql://127.0.0.1:3306/admin-assemble?useUnicode=true&characterEncoding=UTF-8&useSSL=true\r\n    driver-class-name: com.mysql.jdbc.Driver\r\n    #使用druid数据源\r\n    type: com.alibaba.druid.pool.DruidDataSource\r\n    druid:\r\n      initial-size: 5       #初始化时建立物理连接的个数\r\n      min-idle: 5           #最小连接池数量\r\n      max-active: 20        #最大连接池数量\r\n      test-on-borrow: true  #(默认true) 申请连接时执行validationQuery检测连接是否有效,做了这个配置会降低性能\r\n      max-wait: 1000        #获取连接时最大等待时间，单位毫秒。配置了maxWait之后，缺省启用公平锁，\r\n                            #并发效率会有所下降，如果需要可以通过配置useUnfairLock属性为true使用非公平锁。\r\n      stat-view-servlet:\r\n        enabled: true\r\n        url-pattern: /druid/*\r\n        login-username: root\r\n        login-password: 123456\r\n      filter:               #属性类型是字符串，通过别名的方式配置扩展插件，常用的插件有：\r\n                            #监控统计用的filter:stat;日志用的filter:log4j;防御sql注入的filter:wall\r\n        stat:\r\n          log-slow-sql: true\r\n          slow-sql-millis: 1000\r\n          merge-sql: true\r\n        wall:\r\n          config:\r\n            multi-statement-allow: true\r\n  redis:\r\n    host: 127.0.0.1\r\n    port: 6379\r\n    jedis:\r\n      pool:\r\n        max-active: 20\r\n        min-idle: 5\r\n    database: 1', '9a3e666eea1f0b27622b2d9e2a6789fe', '2010-05-05 00:00:00', '2019-12-25 11:28:39', NULL, '127.0.0.1', 'I', '');
INSERT INTO `his_config_info` VALUES (1, 2, 'provider.yaml', 'DEFAULT_GROUP', '', 'spring:\r\n  datasource:\r\n    username: root\r\n    password: 123456\r\n    url: jdbc:mysql://127.0.0.1:3306/admin-assemble?useUnicode=true&characterEncoding=UTF-8&useSSL=true\r\n    driver-class-name: com.mysql.jdbc.Driver\r\n    #使用druid数据源\r\n    type: com.alibaba.druid.pool.DruidDataSource\r\n    druid:\r\n      initial-size: 5       #初始化时建立物理连接的个数\r\n      min-idle: 5           #最小连接池数量\r\n      max-active: 20        #最大连接池数量\r\n      test-on-borrow: true  #(默认true) 申请连接时执行validationQuery检测连接是否有效,做了这个配置会降低性能\r\n      max-wait: 1000        #获取连接时最大等待时间，单位毫秒。配置了maxWait之后，缺省启用公平锁，\r\n                            #并发效率会有所下降，如果需要可以通过配置useUnfairLock属性为true使用非公平锁。\r\n      stat-view-servlet:\r\n        enabled: true\r\n        url-pattern: /druid/*\r\n        login-username: root\r\n        login-password: 123456\r\n      filter:               #属性类型是字符串，通过别名的方式配置扩展插件，常用的插件有：\r\n                            #监控统计用的filter:stat;日志用的filter:log4j;防御sql注入的filter:wall\r\n        stat:\r\n          log-slow-sql: true\r\n          slow-sql-millis: 1000\r\n          merge-sql: true\r\n        wall:\r\n          config:\r\n            multi-statement-allow: true\r\n  redis:\r\n    host: 127.0.0.1\r\n    port: 6379\r\n    jedis:\r\n      pool:\r\n        max-active: 20\r\n        min-idle: 5\r\n    database: 1', '9a3e666eea1f0b27622b2d9e2a6789fe', '2010-05-05 00:00:00', '2019-12-25 11:29:06', NULL, '127.0.0.1', 'U', '');
INSERT INTO `his_config_info` VALUES (1, 3, 'provider.yaml', 'DEFAULT_GROUP', '', 'spring:\r\n  datasource:\r\n    username: root\r\n    password: 123456\r\n    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=UTF-8&useSSL=true\r\n    driver-class-name: com.mysql.jdbc.Driver\r\n    #使用druid数据源\r\n    type: com.alibaba.druid.pool.DruidDataSource\r\n    druid:\r\n      initial-size: 5       #初始化时建立物理连接的个数\r\n      min-idle: 5           #最小连接池数量\r\n      max-active: 20        #最大连接池数量\r\n      test-on-borrow: true  #(默认true) 申请连接时执行validationQuery检测连接是否有效,做了这个配置会降低性能\r\n      max-wait: 1000        #获取连接时最大等待时间，单位毫秒。配置了maxWait之后，缺省启用公平锁，\r\n                            #并发效率会有所下降，如果需要可以通过配置useUnfairLock属性为true使用非公平锁。\r\n      stat-view-servlet:\r\n        enabled: true\r\n        url-pattern: /druid/*\r\n        login-username: root\r\n        login-password: 123456\r\n      filter:               #属性类型是字符串，通过别名的方式配置扩展插件，常用的插件有：\r\n                            #监控统计用的filter:stat;日志用的filter:log4j;防御sql注入的filter:wall\r\n        stat:\r\n          log-slow-sql: true\r\n          slow-sql-millis: 1000\r\n          merge-sql: true\r\n        wall:\r\n          config:\r\n            multi-statement-allow: true\r\n  redis:\r\n    host: 127.0.0.1\r\n    port: 6379\r\n    jedis:\r\n      pool:\r\n        max-active: 20\r\n        min-idle: 5\r\n    database: 1', '8c03fe535b0fb7094097418689a14cca', '2010-05-05 00:00:00', '2019-12-25 11:31:34', NULL, '127.0.0.1', 'U', '');
INSERT INTO `his_config_info` VALUES (1, 4, 'provider.yaml', 'DEFAULT_GROUP', '', 'spring:\r\n  datasource:\r\n    username: root\r\n    password: 123456\r\n    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=UTF-8&useSSL=true\r\n    driver-class-name: com.mysql.jdbc.Driver\r\n    #使用druid数据源\r\n    type: com.alibaba.druid.pool.DruidDataSource\r\n    druid:\r\n      initial-size: 5       #初始化时建立物理连接的个数\r\n      min-idle: 5           #最小连接池数量\r\n      max-active: 20        #最大连接池数量\r\n      test-on-borrow: true  #(默认true) 申请连接时执行validationQuery检测连接是否有效,做了这个配置会降低性能\r\n      max-wait: 1000        #获取连接时最大等待时间，单位毫秒。配置了maxWait之后，缺省启用公平锁，\r\n                            #并发效率会有所下降，如果需要可以通过配置useUnfairLock属性为true使用非公平锁。\r\n      stat-view-servlet:\r\n        enabled: true\r\n        url-pattern: /druid/*\r\n        login-username: root\r\n        login-password: 123456\r\n      filter:               #属性类型是字符串，通过别名的方式配置扩展插件，常用的插件有：\r\n                            #监控统计用的filter:stat;日志用的filter:log4j;防御sql注入的filter:wall\r\n        stat:\r\n          log-slow-sql: true\r\n          slow-sql-millis: 1000\r\n          merge-sql: true\r\n        wall:\r\n          config:\r\n            multi-statement-allow: true\r\n  redis:\r\n    host: 127.0.0.1\r\n    port: 6379\r\n    jedis:\r\n      pool:\r\n        max-active: 20\r\n        min-idle: 5\r\n    database: 1', '8c03fe535b0fb7094097418689a14cca', '2010-05-05 00:00:00', '2019-12-25 16:12:32', NULL, '127.0.0.1', 'U', '');
INSERT INTO `his_config_info` VALUES (1, 5, 'provider.yaml', 'DEFAULT_GROUP', '', 'spring:\r\n  datasource:\r\n    username: root\r\n    password: 123456\r\n    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=UTF-8&useSSL=true\r\n    driver-class-name: com.mysql.jdbc.Driver\r\n    #使用druid数据源\r\n    type: com.alibaba.druid.pool.DruidDataSource\r\n    druid:\r\n      initial-size: 5       #初始化时建立物理连接的个数\r\n      min-idle: 5           #最小连接池数量\r\n      max-active: 20        #最大连接池数量\r\n      test-on-borrow: true  #(默认true) 申请连接时执行validationQuery检测连接是否有效,做了这个配置会降低性能\r\n      max-wait: 1000        #获取连接时最大等待时间，单位毫秒。配置了maxWait之后，缺省启用公平锁，\r\n                            #并发效率会有所下降，如果需要可以通过配置useUnfairLock属性为true使用非公平锁。\r\n      stat-view-servlet:\r\n        enabled: true\r\n        url-pattern: /druid/*\r\n        login-username: root\r\n        login-password: 123456\r\n      filter:               #属性类型是字符串，通过别名的方式配置扩展插件，常用的插件有：\r\n                            #监控统计用的filter:stat;日志用的filter:log4j;防御sql注入的filter:wall\r\n        stat:\r\n          log-slow-sql: true\r\n          slow-sql-millis: 1000\r\n          merge-sql: true\r\n        wall:\r\n          config:\r\n            multi-statement-allow: true\r\n  redis:\r\n    host: 127.0.0.1\r\n    port: 6379\r\n    jedis:\r\n      pool:\r\n        max-active: 20\r\n        min-idle: 5\r\n    database: 1', '8c03fe535b0fb7094097418689a14cca', '2010-05-05 00:00:00', '2019-12-25 18:15:27', NULL, '127.0.0.1', 'U', '');
INSERT INTO `his_config_info` VALUES (1, 6, 'provider.yaml', 'DEFAULT_GROUP', '', 'spring:\r\n  datasource:\r\n    username: root\r\n    password: 123456\r\n    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=UTF-8&useSSL=true\r\n    driver-class-name: com.mysql.jdbc.Driver\r\n    type: com.alibaba.druid.pool.DruidDataSource\r\n    druid:\r\n      initial-size: 5       \r\n      min-idle: 5           \r\n      max-active: 20        \r\n      test-on-borrow: true  \r\n      max-wait: 1000        \r\n  \r\n      stat-view-servlet:\r\n        enabled: true\r\n        url-pattern: /druid/*\r\n        login-username: root\r\n        login-password: 123456\r\n      filter:              \r\n        stat:\r\n          log-slow-sql: true\r\n          slow-sql-millis: 1000\r\n          merge-sql: true\r\n        wall:\r\n          config:\r\n            multi-statement-allow: true\r\n  redis:\r\n    host: 127.0.0.1\r\n    port: 6379\r\n    jedis:\r\n      pool:\r\n        max-active: 20\r\n        min-idle: 5\r\n    database: 1', 'fa3e538aff5eaa2bdfd54fc735dffdee', '2010-05-05 00:00:00', '2019-12-26 10:35:38', NULL, '127.0.0.1', 'U', '');
INSERT INTO `his_config_info` VALUES (1, 7, 'provider.yaml', 'DEFAULT_GROUP', '', 'spring:\r\n  datasource:\r\n    username: root\r\n    password: 123456\r\n    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=UTF-8&useSSL=true\r\n    driver-class-name: com.mysql.jdbc.Driver\r\n    type: com.alibaba.druid.pool.DruidDataSource\r\n    druid:\r\n      initial-size: 5       \r\n      min-idle: 5           \r\n      max-active: 20        \r\n      test-on-borrow: true  \r\n      max-wait: 1000        \r\n  \r\n      stat-view-servlet:\r\n        enabled: true\r\n        url-pattern: /druid/*\r\n        login-username: root\r\n        login-password: 123456\r\n      filter:              \r\n        stat:\r\n          log-slow-sql: true\r\n          slow-sql-millis: 1000\r\n          merge-sql: true\r\n        wall:\r\n          config:\r\n            multi-statement-allow: true\r\n  redis:\r\n    host: 127.0.0.1\r\n    port: 6380\r\n    jedis:\r\n      pool:\r\n        max-active: 20\r\n        min-idle: 5\r\n    database: 1', 'bee4e1608f71868bad73c4096a104e28', '2010-05-05 00:00:00', '2019-12-26 16:57:52', NULL, '127.0.0.1', 'U', '');
INSERT INTO `his_config_info` VALUES (1, 8, 'provider.yaml', 'DEFAULT_GROUP', '', 'spring:\r\n  datasource:\r\n    username: root\r\n    password: 123456\r\n    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=UTF-8&useSSL=true\r\n    driver-class-name: com.mysql.jdbc.Driver\r\n    type: com.alibaba.druid.pool.DruidDataSource\r\n    druid:\r\n      initial-size: 5       \r\n      min-idle: 5           \r\n      max-active: 20        \r\n      test-on-borrow: true  \r\n      max-wait: 1000        \r\n  \r\n      stat-view-servlet:\r\n        enabled: true\r\n        url-pattern: /druid/*\r\n        login-username: root\r\n        login-password: 123456\r\n      filter:              \r\n        stat:\r\n          log-slow-sql: true\r\n          slow-sql-millis: 1000\r\n          merge-sql: true\r\n        wall:\r\n          config:\r\n            multi-statement-allow: true\r\n  redis:\r\n    host: 127.0.0.1\r\n    port: 6380\r\n    jedis:\r\n      pool:\r\n        max-active: 20\r\n        min-idle: 5\r\n    database: 1', 'bee4e1608f71868bad73c4096a104e28', '2010-05-05 00:00:00', '2019-12-26 17:01:11', NULL, '127.0.0.1', 'U', '');
INSERT INTO `his_config_info` VALUES (1, 9, 'provider.yaml', 'DEFAULT_GROUP', '', 'spring:\r\n  datasource:\r\n    username: root\r\n    password: 123456\r\n    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=UTF-8&useSSL=true\r\n    driver-class-name: com.mysql.jdbc.Driver\r\n    type: com.alibaba.druid.pool.DruidDataSource\r\n    druid:\r\n      initial-size: 5       \r\n      min-idle: 5           \r\n      max-active: 20        \r\n      test-on-borrow: true  \r\n      max-wait: 1000        \r\n  \r\n      stat-view-servlet:\r\n        enabled: true\r\n        url-pattern: /druid/*\r\n        login-username: root\r\n        login-password: 123456\r\n      filter:              \r\n        stat:\r\n          log-slow-sql: true\r\n          slow-sql-millis: 1000\r\n          merge-sql: true\r\n        wall:\r\n          config:\r\n            multi-statement-allow: true\r\n  redis:\r\n    host: 127.0.0.1\r\n    port: 6380\r\n    jedis:\r\n      pool:\r\n        max-active: 20\r\n        min-idle: 5\r\n    database: 1\r\n\r\ntest: tttt', '138282272b2768a8a69252496ad43a8e', '2010-05-05 00:00:00', '2019-12-26 17:03:10', NULL, '127.0.0.1', 'U', '');
INSERT INTO `his_config_info` VALUES (1, 10, 'provider.yaml', 'DEFAULT_GROUP', '', 'spring:\r\n  datasource:\r\n    username: root\r\n    password: 123456\r\n    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=UTF-8&useSSL=true\r\n    driver-class-name: com.mysql.jdbc.Driver\r\n    type: com.alibaba.druid.pool.DruidDataSource\r\n    druid:\r\n      initial-size: 5       \r\n      min-idle: 5           \r\n      max-active: 20        \r\n      test-on-borrow: true  \r\n      max-wait: 1000        \r\n  \r\n      stat-view-servlet:\r\n        enabled: true\r\n        url-pattern: /druid/*\r\n        login-username: root\r\n        login-password: 123456\r\n      filter:              \r\n        stat:\r\n          log-slow-sql: true\r\n          slow-sql-millis: 1000\r\n          merge-sql: true\r\n        wall:\r\n          config:\r\n            multi-statement-allow: true\r\n  redis:\r\n    host: 127.0.0.1\r\n    port: 6380\r\n    jedis:\r\n      pool:\r\n        max-active: 20\r\n        min-idle: 5\r\n    database: 1\r\n\r\ntest: 123', '98d1bddf91eb972bc7947547816f809b', '2010-05-05 00:00:00', '2019-12-26 17:06:47', NULL, '127.0.0.1', 'U', '');
INSERT INTO `his_config_info` VALUES (1, 11, 'provider.yaml', 'DEFAULT_GROUP', '', 'spring:\r\n  datasource:\r\n    username: root\r\n    password: 123456\r\n    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=UTF-8&useSSL=true\r\n    driver-class-name: com.mysql.jdbc.Driver\r\n    type: com.alibaba.druid.pool.DruidDataSource\r\n    druid:\r\n      initial-size: 5       \r\n      min-idle: 5           \r\n      max-active: 20        \r\n      test-on-borrow: true  \r\n      max-wait: 1000        \r\n  \r\n      stat-view-servlet:\r\n        enabled: true\r\n        url-pattern: /druid/*\r\n        login-username: root\r\n        login-password: 123456\r\n      filter:              \r\n        stat:\r\n          log-slow-sql: true\r\n          slow-sql-millis: 1000\r\n          merge-sql: true\r\n        wall:\r\n          config:\r\n            multi-statement-allow: true\r\n  redis:\r\n    host: 127.0.0.1\r\n    port: 6380\r\n    jedis:\r\n      pool:\r\n        max-active: 20\r\n        min-idle: 5\r\n    database: 1\r\n\r\nuseLocalCache: true', '2ad699dd033b8a96a63fdeac4bf8159e', '2010-05-05 00:00:00', '2019-12-26 17:42:02', NULL, '127.0.0.1', 'U', '');
INSERT INTO `his_config_info` VALUES (1, 12, 'provider.yaml', 'DEFAULT_GROUP', '', 'useLocalCache: true', '00b77727c9b4a661b8ae12cd7de1395f', '2010-05-05 00:00:00', '2019-12-26 17:45:31', NULL, '127.0.0.1', 'U', '');
INSERT INTO `his_config_info` VALUES (0, 13, 'provider.yaml', 'DEFAULT_GROUP', '', 'spring:\r\n  datasource:\r\n    username: root\r\n    password: 123456\r\n    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=UTF-8&useSSL=true\r\n    driver-class-name: com.mysql.jdbc.Driver\r\n    type: com.alibaba.druid.pool.DruidDataSource\r\n    druid:\r\n      initial-size: 5       \r\n      min-idle: 5           \r\n      max-active: 20        \r\n      test-on-borrow: true  \r\n      max-wait: 1000        \r\n  \r\n      stat-view-servlet:\r\n        enabled: true\r\n        url-pattern: /druid/*\r\n        login-username: root\r\n        login-password: 123456\r\n      filter:              \r\n        stat:\r\n          log-slow-sql: true\r\n          slow-sql-millis: 1000\r\n          merge-sql: true\r\n        wall:\r\n          config:\r\n            multi-statement-allow: true\r\n  redis:\r\n    host: 127.0.0.1\r\n    port: 6380\r\n    jedis:\r\n      pool:\r\n        max-active: 20\r\n        min-idle: 5\r\n    database: 1\r\n\r\nuseLocalCache: true', '2ad699dd033b8a96a63fdeac4bf8159e', '2010-05-05 00:00:00', '2019-12-26 17:45:52', NULL, '127.0.0.1', 'I', '2572cfa6-38d4-4a72-812b-3347fe50aa98');
INSERT INTO `his_config_info` VALUES (1, 14, 'provider.yaml', 'DEFAULT_GROUP', '', 'spring:\r\n  datasource:\r\n    username: root\r\n    password: 123456\r\n    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=UTF-8&useSSL=true\r\n    driver-class-name: com.mysql.jdbc.Driver\r\n    type: com.alibaba.druid.pool.DruidDataSource\r\n    druid:\r\n      initial-size: 5       \r\n      min-idle: 5           \r\n      max-active: 20        \r\n      test-on-borrow: true  \r\n      max-wait: 1000        \r\n  \r\n      stat-view-servlet:\r\n        enabled: true\r\n        url-pattern: /druid/*\r\n        login-username: root\r\n        login-password: 123456\r\n      filter:              \r\n        stat:\r\n          log-slow-sql: true\r\n          slow-sql-millis: 1000\r\n          merge-sql: true\r\n        wall:\r\n          config:\r\n            multi-statement-allow: true\r\n  redis:\r\n    host: 127.0.0.1\r\n    port: 6380\r\n    jedis:\r\n      pool:\r\n        max-active: 20\r\n        min-idle: 5\r\n    database: 1\r\n\r\nuseLocalCache: true', '2ad699dd033b8a96a63fdeac4bf8159e', '2010-05-05 00:00:00', '2019-12-26 17:48:51', NULL, '127.0.0.1', 'U', '');
INSERT INTO `his_config_info` VALUES (1, 15, 'provider.yaml', 'DEFAULT_GROUP', '', 'spring:\r\n  datasource:\r\n    username: root\r\n    password: 123456\r\n    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=UTF-8&useSSL=true\r\n    driver-class-name: com.mysql.jdbc.Driver\r\n    type: com.alibaba.druid.pool.DruidDataSource\r\n    druid:\r\n      initial-size: 5       \r\n      min-idle: 5           \r\n      max-active: 20        \r\n      test-on-borrow: true  \r\n      max-wait: 1000        \r\n  \r\n      stat-view-servlet:\r\n        enabled: true\r\n        url-pattern: /druid/*\r\n        login-username: root\r\n        login-password: 123456\r\n      filter:              \r\n        stat:\r\n          log-slow-sql: true\r\n          slow-sql-millis: 1000\r\n          merge-sql: true\r\n        wall:\r\n          config:\r\n            multi-statement-allow: true\r\n  redis:\r\n    host: 127.0.0.1\r\n    port: 6380\r\n    jedis:\r\n      pool:\r\n        max-active: 20\r\n        min-idle: 5\r\n    database: 1\r\n\r\nuseLocalCache: false', '1a4063407a5a50fe5ddf89e0d4051788', '2010-05-05 00:00:00', '2019-12-26 17:49:25', NULL, '127.0.0.1', 'U', '');
INSERT INTO `his_config_info` VALUES (1, 16, 'provider.yaml', 'DEFAULT_GROUP', '', 'spring:\r\n  datasource:\r\n    username: root\r\n    password: 123456\r\n    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=UTF-8&useSSL=true\r\n    driver-class-name: com.mysql.jdbc.Driver\r\n    type: com.alibaba.druid.pool.DruidDataSource\r\n    druid:\r\n      initial-size: 5       \r\n      min-idle: 5           \r\n      max-active: 20        \r\n      test-on-borrow: true  \r\n      max-wait: 1000        \r\n  \r\n      stat-view-servlet:\r\n        enabled: true\r\n        url-pattern: /druid/*\r\n        login-username: root\r\n        login-password: 123456\r\n      filter:              \r\n        stat:\r\n          log-slow-sql: true\r\n          slow-sql-millis: 1000\r\n          merge-sql: true\r\n        wall:\r\n          config:\r\n            multi-statement-allow: true\r\n  redis:\r\n    host: 127.0.0.1\r\n    port: 6380\r\n    jedis:\r\n      pool:\r\n        max-active: 20\r\n        min-idle: 5\r\n    database: 1\r\n\r\nuseLocalCache: false', '1a4063407a5a50fe5ddf89e0d4051788', '2010-05-05 00:00:00', '2019-12-26 17:49:47', NULL, '127.0.0.1', 'U', '');
INSERT INTO `his_config_info` VALUES (1, 17, 'provider.yaml', 'DEFAULT_GROUP', '', 'spring:\r\n  datasource:\r\n    username: root\r\n    password: 123456\r\n    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=UTF-8&useSSL=true\r\n    driver-class-name: com.mysql.jdbc.Driver\r\n    type: com.alibaba.druid.pool.DruidDataSource\r\n    druid:\r\n      initial-size: 5       \r\n      min-idle: 5           \r\n      max-active: 20        \r\n      test-on-borrow: true  \r\n      max-wait: 1000        \r\n  \r\n      stat-view-servlet:\r\n        enabled: true\r\n        url-pattern: /druid/*\r\n        login-username: root\r\n        login-password: 123456\r\n      filter:              \r\n        stat:\r\n          log-slow-sql: true\r\n          slow-sql-millis: 1000\r\n          merge-sql: true\r\n        wall:\r\n          config:\r\n            multi-statement-allow: true\r\n  redis:\r\n    host: 127.0.0.1\r\n    port: 6380\r\n    jedis:\r\n      pool:\r\n        max-active: 20\r\n        min-idle: 5\r\n    database: 1\r\n\r\nuseLocalCache: true', '2ad699dd033b8a96a63fdeac4bf8159e', '2010-05-05 00:00:00', '2019-12-26 17:50:01', NULL, '127.0.0.1', 'U', '');
INSERT INTO `his_config_info` VALUES (1, 18, 'provider.yaml', 'DEFAULT_GROUP', '', 'spring:\r\n  datasource:\r\n    username: root\r\n    password: 123456\r\n    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=UTF-8&useSSL=true\r\n    driver-class-name: com.mysql.jdbc.Driver\r\n    type: com.alibaba.druid.pool.DruidDataSource\r\n    druid:\r\n      initial-size: 5       \r\n      min-idle: 5           \r\n      max-active: 20        \r\n      test-on-borrow: true  \r\n      max-wait: 1000        \r\n  \r\n      stat-view-servlet:\r\n        enabled: true\r\n        url-pattern: /druid/*\r\n        login-username: root\r\n        login-password: 123456\r\n      filter:              \r\n        stat:\r\n          log-slow-sql: true\r\n          slow-sql-millis: 1000\r\n          merge-sql: true\r\n        wall:\r\n          config:\r\n            multi-statement-allow: true\r\n  redis:\r\n    host: 127.0.0.1\r\n    port: 6380\r\n    jedis:\r\n      pool:\r\n        max-active: 20\r\n        min-idle: 5\r\n    database: 1\r\n\r\nuseLocalCache: false', '1a4063407a5a50fe5ddf89e0d4051788', '2010-05-05 00:00:00', '2019-12-26 17:50:59', NULL, '127.0.0.1', 'U', '');
INSERT INTO `his_config_info` VALUES (1, 19, 'provider.yaml', 'DEFAULT_GROUP', '', 'spring:\r\n  datasource:\r\n    username: root\r\n    password: 123456\r\n    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=UTF-8&useSSL=true\r\n    driver-class-name: com.mysql.jdbc.Driver\r\n    type: com.alibaba.druid.pool.DruidDataSource\r\n    druid:\r\n      initial-size: 5       \r\n      min-idle: 5           \r\n      max-active: 20        \r\n      test-on-borrow: true  \r\n      max-wait: 1000        \r\n  \r\n      stat-view-servlet:\r\n        enabled: true\r\n        url-pattern: /druid/*\r\n        login-username: root\r\n        login-password: 123456\r\n      filter:              \r\n        stat:\r\n          log-slow-sql: true\r\n          slow-sql-millis: 1000\r\n          merge-sql: true\r\n        wall:\r\n          config:\r\n            multi-statement-allow: true\r\n  redis:\r\n    host: 127.0.0.1\r\n    port: 6380\r\n    jedis:\r\n      pool:\r\n        max-active: 20\r\n        min-idle: 5\r\n    database: 1\r\n\r\nuseLocalCache: true', '2ad699dd033b8a96a63fdeac4bf8159e', '2010-05-05 00:00:00', '2019-12-26 17:51:06', NULL, '127.0.0.1', 'U', '');
INSERT INTO `his_config_info` VALUES (1, 20, 'provider.yaml', 'DEFAULT_GROUP', '', 'spring:\r\n  datasource:\r\n    username: root\r\n    password: 123456\r\n    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=UTF-8&useSSL=true\r\n    driver-class-name: com.mysql.jdbc.Driver\r\n    type: com.alibaba.druid.pool.DruidDataSource\r\n    druid:\r\n      initial-size: 5       \r\n      min-idle: 5           \r\n      max-active: 20        \r\n      test-on-borrow: true  \r\n      max-wait: 1000        \r\n  \r\n      stat-view-servlet:\r\n        enabled: true\r\n        url-pattern: /druid/*\r\n        login-username: root\r\n        login-password: 123456\r\n      filter:              \r\n        stat:\r\n          log-slow-sql: true\r\n          slow-sql-millis: 1000\r\n          merge-sql: true\r\n        wall:\r\n          config:\r\n            multi-statement-allow: true\r\n  redis:\r\n    host: 127.0.0.1\r\n    port: 6380\r\n    jedis:\r\n      pool:\r\n        max-active: 20\r\n        min-idle: 5\r\n    database: 1\r\n\r\nuseLocalCache: 123', '97168e596c760eae850ce47b44d51a28', '2010-05-05 00:00:00', '2019-12-26 17:51:34', NULL, '127.0.0.1', 'U', '');
INSERT INTO `his_config_info` VALUES (1, 21, 'provider.yaml', 'DEFAULT_GROUP', '', 'spring:\r\n  datasource:\r\n    username: root\r\n    password: 123456\r\n    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=UTF-8&useSSL=true\r\n    driver-class-name: com.mysql.jdbc.Driver\r\n    type: com.alibaba.druid.pool.DruidDataSource\r\n    druid:\r\n      initial-size: 5       \r\n      min-idle: 5           \r\n      max-active: 20        \r\n      test-on-borrow: true  \r\n      max-wait: 1000        \r\n  \r\n      stat-view-servlet:\r\n        enabled: true\r\n        url-pattern: /druid/*\r\n        login-username: root\r\n        login-password: 123456\r\n      filter:              \r\n        stat:\r\n          log-slow-sql: true\r\n          slow-sql-millis: 1000\r\n          merge-sql: true\r\n        wall:\r\n          config:\r\n            multi-statement-allow: true\r\n  redis:\r\n    host: 127.0.0.1\r\n    port: 6380\r\n    jedis:\r\n      pool:\r\n        max-active: 20\r\n        min-idle: 5\r\n    database: 1\r\n\r\nuseLocalCache: false', '1a4063407a5a50fe5ddf89e0d4051788', '2010-05-05 00:00:00', '2019-12-26 17:52:20', NULL, '127.0.0.1', 'U', '');
INSERT INTO `his_config_info` VALUES (1, 22, 'provider.yaml', 'DEFAULT_GROUP', '', 'spring:\r\n  datasource:\r\n    username: root\r\n    password: 123456\r\n    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=UTF-8&useSSL=true\r\n    driver-class-name: com.mysql.jdbc.Driver\r\n    type: com.alibaba.druid.pool.DruidDataSource\r\n    druid:\r\n      initial-size: 5       \r\n      min-idle: 5           \r\n      max-active: 20        \r\n      test-on-borrow: true  \r\n      max-wait: 1000        \r\n  \r\n      stat-view-servlet:\r\n        enabled: true\r\n        url-pattern: /druid/*\r\n        login-username: root\r\n        login-password: 123456\r\n      filter:              \r\n        stat:\r\n          log-slow-sql: true\r\n          slow-sql-millis: 1000\r\n          merge-sql: true\r\n        wall:\r\n          config:\r\n            multi-statement-allow: true\r\n  redis:\r\n    host: 127.0.0.1\r\n    port: 6380\r\n    jedis:\r\n      pool:\r\n        max-active: 20\r\n        min-idle: 5\r\n    database: 1\r\n\r\nuseLocalCache: true', '2ad699dd033b8a96a63fdeac4bf8159e', '2010-05-05 00:00:00', '2019-12-26 17:53:01', NULL, '127.0.0.1', 'U', '');
INSERT INTO `his_config_info` VALUES (1, 23, 'provider.yaml', 'DEFAULT_GROUP', '', 'spring:\r\n  datasource:\r\n    username: root\r\n    password: 123456\r\n    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=UTF-8&useSSL=true\r\n    driver-class-name: com.mysql.jdbc.Driver\r\n    type: com.alibaba.druid.pool.DruidDataSource\r\n    druid:\r\n      initial-size: 5       \r\n      min-idle: 5           \r\n      max-active: 20        \r\n      test-on-borrow: true  \r\n      max-wait: 1000        \r\n  \r\n      stat-view-servlet:\r\n        enabled: true\r\n        url-pattern: /druid/*\r\n        login-username: root\r\n        login-password: 123456\r\n      filter:              \r\n        stat:\r\n          log-slow-sql: true\r\n          slow-sql-millis: 1000\r\n          merge-sql: true\r\n        wall:\r\n          config:\r\n            multi-statement-allow: true\r\n  redis:\r\n    host: 127.0.0.1\r\n    port: 6380\r\n    jedis:\r\n      pool:\r\n        max-active: 20\r\n        min-idle: 5\r\n    database: 1\r\n\r\nuseLocalCache: false', '1a4063407a5a50fe5ddf89e0d4051788', '2010-05-05 00:00:00', '2019-12-26 17:54:31', NULL, '127.0.0.1', 'U', '');
INSERT INTO `his_config_info` VALUES (1, 24, 'provider.yaml', 'DEFAULT_GROUP', '', 'spring:\r\n  datasource:\r\n    username: root\r\n    password: 123456\r\n    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=UTF-8&useSSL=true\r\n    driver-class-name: com.mysql.jdbc.Driver\r\n    type: com.alibaba.druid.pool.DruidDataSource\r\n    druid:\r\n      initial-size: 5       \r\n      min-idle: 5           \r\n      max-active: 20        \r\n      test-on-borrow: true  \r\n      max-wait: 1000        \r\n  \r\n      stat-view-servlet:\r\n        enabled: true\r\n        url-pattern: /druid/*\r\n        login-username: root\r\n        login-password: 123456\r\n      filter:              \r\n        stat:\r\n          log-slow-sql: true\r\n          slow-sql-millis: 1000\r\n          merge-sql: true\r\n        wall:\r\n          config:\r\n            multi-statement-allow: true\r\n  redis:\r\n    host: 127.0.0.1\r\n    port: 6380\r\n    jedis:\r\n      pool:\r\n        max-active: 20\r\n        min-idle: 5\r\n    database: 1\r\n\r\nuseLocalCache: true', '2ad699dd033b8a96a63fdeac4bf8159e', '2010-05-05 00:00:00', '2019-12-26 17:56:20', NULL, '127.0.0.1', 'U', '');
INSERT INTO `his_config_info` VALUES (1, 25, 'provider.yaml', 'DEFAULT_GROUP', '', 'spring:\r\n  datasource:\r\n    username: root\r\n    password: 123456\r\n    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=UTF-8&useSSL=true\r\n    driver-class-name: com.mysql.jdbc.Driver\r\n    type: com.alibaba.druid.pool.DruidDataSource\r\n    druid:\r\n      initial-size: 5       \r\n      min-idle: 5           \r\n      max-active: 20        \r\n      test-on-borrow: true  \r\n      max-wait: 1000        \r\n  \r\n      stat-view-servlet:\r\n        enabled: true\r\n        url-pattern: /druid/*\r\n        login-username: root\r\n        login-password: 123456\r\n      filter:              \r\n        stat:\r\n          log-slow-sql: true\r\n          slow-sql-millis: 1000\r\n          merge-sql: true\r\n        wall:\r\n          config:\r\n            multi-statement-allow: true\r\n  redis:\r\n    host: 127.0.0.1\r\n    port: 6380\r\n    jedis:\r\n      pool:\r\n        max-active: 20\r\n        min-idle: 5\r\n    database: 1\r\n\r\nuseLocalCache: false', '1a4063407a5a50fe5ddf89e0d4051788', '2010-05-05 00:00:00', '2019-12-26 17:57:19', NULL, '127.0.0.1', 'U', '');
INSERT INTO `his_config_info` VALUES (1, 26, 'provider.yaml', 'DEFAULT_GROUP', '', 'spring:\r\n  datasource:\r\n    username: root\r\n    password: 123456\r\n    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=UTF-8&useSSL=true\r\n    driver-class-name: com.mysql.jdbc.Driver\r\n    type: com.alibaba.druid.pool.DruidDataSource\r\n    druid:\r\n      initial-size: 5       \r\n      min-idle: 5           \r\n      max-active: 20        \r\n      test-on-borrow: true  \r\n      max-wait: 1000        \r\n  \r\n      stat-view-servlet:\r\n        enabled: true\r\n        url-pattern: /druid/*\r\n        login-username: root\r\n        login-password: 123456\r\n      filter:              \r\n        stat:\r\n          log-slow-sql: true\r\n          slow-sql-millis: 1000\r\n          merge-sql: true\r\n        wall:\r\n          config:\r\n            multi-statement-allow: true\r\n  redis:\r\n    host: 127.0.0.1\r\n    port: 6380\r\n    jedis:\r\n      pool:\r\n        max-active: 20\r\n        min-idle: 5\r\n    database: 1\r\n\r\nuseLocalCache: true', '2ad699dd033b8a96a63fdeac4bf8159e', '2010-05-05 00:00:00', '2019-12-26 18:54:14', NULL, '127.0.0.1', 'U', '');
INSERT INTO `his_config_info` VALUES (1, 27, 'provider.yaml', 'DEFAULT_GROUP', '', 'spring:\r\n  datasource:\r\n    username: root\r\n    password: 123456\r\n    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=UTF-8&useSSL=true\r\n    driver-class-name: com.mysql.jdbc.Driver\r\n    type: com.alibaba.druid.pool.DruidDataSource\r\n    druid:\r\n      initial-size: 5       \r\n      min-idle: 5           \r\n      max-active: 20        \r\n      test-on-borrow: true  \r\n      max-wait: 1000        \r\n  \r\n      stat-view-servlet:\r\n        enabled: true\r\n        url-pattern: /druid/*\r\n        login-username: root\r\n        login-password: 123456\r\n      filter:              \r\n        stat:\r\n          log-slow-sql: true\r\n          slow-sql-millis: 1000\r\n          merge-sql: true\r\n        wall:\r\n          config:\r\n            multi-statement-allow: true\r\n  redis:\r\n    host: 127.0.0.1\r\n    port: 6380\r\n    jedis:\r\n      pool:\r\n        max-active: 20\r\n        min-idle: 5\r\n    database: 1\r\n\r\nuseLocalCache: true', '2ad699dd033b8a96a63fdeac4bf8159e', '2010-05-05 00:00:00', '2019-12-26 18:56:25', NULL, '127.0.0.1', 'U', '');
INSERT INTO `his_config_info` VALUES (13, 28, 'provider.yaml', 'DEFAULT_GROUP', '', 'spring:\r\n  datasource:\r\n    username: root\r\n    password: 123456\r\n    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=UTF-8&useSSL=true\r\n    driver-class-name: com.mysql.jdbc.Driver\r\n    type: com.alibaba.druid.pool.DruidDataSource\r\n    druid:\r\n      initial-size: 5       \r\n      min-idle: 5           \r\n      max-active: 20        \r\n      test-on-borrow: true  \r\n      max-wait: 1000        \r\n  \r\n      stat-view-servlet:\r\n        enabled: true\r\n        url-pattern: /druid/*\r\n        login-username: root\r\n        login-password: 123456\r\n      filter:              \r\n        stat:\r\n          log-slow-sql: true\r\n          slow-sql-millis: 1000\r\n          merge-sql: true\r\n        wall:\r\n          config:\r\n            multi-statement-allow: true\r\n  redis:\r\n    host: 127.0.0.1\r\n    port: 6380\r\n    jedis:\r\n      pool:\r\n        max-active: 20\r\n        min-idle: 5\r\n    database: 1\r\n\r\nuseLocalCache: true', '2ad699dd033b8a96a63fdeac4bf8159e', '2010-05-05 00:00:00', '2019-12-26 18:57:02', NULL, '127.0.0.1', 'U', '2572cfa6-38d4-4a72-812b-3347fe50aa98');
INSERT INTO `his_config_info` VALUES (13, 29, 'provider.yaml', 'DEFAULT_GROUP', '', 'spring:\r\n  datasource:\r\n    username: root\r\n    password: 123456\r\n    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=UTF-8&useSSL=false\r\n    driver-class-name: com.mysql.jdbc.Driver\r\n    type: com.alibaba.druid.pool.DruidDataSource\r\n    druid:\r\n      initial-size: 5       \r\n      min-idle: 5           \r\n      max-active: 20        \r\n      test-on-borrow: true  \r\n      max-wait: 1000        \r\n  \r\n      stat-view-servlet:\r\n        enabled: true\r\n        url-pattern: /druid/*\r\n        login-username: root\r\n        login-password: 123456\r\n      filter:              \r\n        stat:\r\n          log-slow-sql: true\r\n          slow-sql-millis: 1000\r\n          merge-sql: true\r\n        wall:\r\n          config:\r\n            multi-statement-allow: true\r\n  redis:\r\n    host: 127.0.0.1\r\n    port: 6380\r\n    jedis:\r\n      pool:\r\n        max-active: 20\r\n        min-idle: 5\r\n    database: 1\r\n\r\nuseLocalCache: true', 'da92b01f9abf83dcd453d445a807be03', '2010-05-05 00:00:00', '2019-12-26 19:12:01', NULL, '127.0.0.1', 'U', '2572cfa6-38d4-4a72-812b-3347fe50aa98');
INSERT INTO `his_config_info` VALUES (0, 30, 'provider.yaml', 'PROVIDER_GROUP', '', 'spring:\r\n  datasource:\r\n    username: root\r\n    password: 123456\r\n    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=UTF-8&useSSL=false\r\n    driver-class-name: com.mysql.jdbc.Driver\r\n    type: com.alibaba.druid.pool.DruidDataSource\r\n    druid:\r\n      initial-size: 5       \r\n      min-idle: 5           \r\n      max-active: 20        \r\n      test-on-borrow: true  \r\n      max-wait: 1000        \r\n  \r\n      stat-view-servlet:\r\n        enabled: true\r\n        url-pattern: /druid/*\r\n        login-username: root\r\n        login-password: 123456\r\n      filter:              \r\n        stat:\r\n          log-slow-sql: true\r\n          slow-sql-millis: 1000\r\n          merge-sql: true\r\n        wall:\r\n          config:\r\n            multi-statement-allow: true\r\n  redis:\r\n    host: 127.0.0.1\r\n    port: 6380\r\n    jedis:\r\n      pool:\r\n        max-active: 20\r\n        min-idle: 5\r\n    database: 1\r\n\r\nuseLocalCache: true', 'da92b01f9abf83dcd453d445a807be03', '2010-05-05 00:00:00', '2019-12-26 19:48:30', NULL, '127.0.0.1', 'I', '2572cfa6-38d4-4a72-812b-3347fe50aa98');
INSERT INTO `his_config_info` VALUES (13, 31, 'provider.yaml', 'DEFAULT_GROUP', '', 'spring:\r\n  datasource:\r\n    username: root\r\n    password: 123456\r\n    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=UTF-8&useSSL=false\r\n    driver-class-name: com.mysql.jdbc.Driver\r\n    type: com.alibaba.druid.pool.DruidDataSource\r\n    druid:\r\n      initial-size: 5       \r\n      min-idle: 5           \r\n      max-active: 20        \r\n      test-on-borrow: true  \r\n      max-wait: 1000        \r\n  \r\n      stat-view-servlet:\r\n        enabled: true\r\n        url-pattern: /druid/*\r\n        login-username: root\r\n        login-password: 123456\r\n      filter:              \r\n        stat:\r\n          log-slow-sql: true\r\n          slow-sql-millis: 1000\r\n          merge-sql: true\r\n        wall:\r\n          config:\r\n            multi-statement-allow: true\r\n  redis:\r\n    host: 127.0.0.1\r\n    port: 6380\r\n    jedis:\r\n      pool:\r\n        max-active: 20\r\n        min-idle: 5\r\n    database: 1\r\n\r\nuseLocalCache: true\r\n\r\nserver:\r\n  port: 8081', 'a942f6f275658829b7365dc089c707c7', '2010-05-05 00:00:00', '2019-12-26 19:48:41', NULL, '127.0.0.1', 'D', '2572cfa6-38d4-4a72-812b-3347fe50aa98');
INSERT INTO `his_config_info` VALUES (0, 32, 'provider.yaml', 'PROVIDER_GROUP', '', 'spring:\r\n  datasource:\r\n    username: root\r\n    password: 123456\r\n    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=UTF-8&useSSL=false\r\n    driver-class-name: com.mysql.jdbc.Driver\r\n    type: com.alibaba.druid.pool.DruidDataSource\r\n    druid:\r\n      initial-size: 5       \r\n      min-idle: 5           \r\n      max-active: 20        \r\n      test-on-borrow: true  \r\n      max-wait: 1000        \r\n  \r\n      stat-view-servlet:\r\n        enabled: true\r\n        url-pattern: /druid/*\r\n        login-username: root\r\n        login-password: 123456\r\n      filter:              \r\n        stat:\r\n          log-slow-sql: true\r\n          slow-sql-millis: 1000\r\n          merge-sql: true\r\n        wall:\r\n          config:\r\n            multi-statement-allow: true\r\n  redis:\r\n    host: 127.0.0.1\r\n    port: 6380\r\n    jedis:\r\n      pool:\r\n        max-active: 20\r\n        min-idle: 5\r\n    database: 1\r\n\r\nuseLocalCache: true', 'da92b01f9abf83dcd453d445a807be03', '2010-05-05 00:00:00', '2019-12-26 19:50:04', NULL, '127.0.0.1', 'I', '2d5193c9-4b61-453e-8eae-e0fae3b516e1');
INSERT INTO `his_config_info` VALUES (0, 33, 'consumer.yaml', 'CONSUMER_GROUP', '', 'PROVIDER_GROUP: true', 'de2ab4aa468ead3cf104f711e74428bd', '2010-05-05 00:00:00', '2019-12-26 19:51:18', NULL, '127.0.0.1', 'I', '2572cfa6-38d4-4a72-812b-3347fe50aa98');
INSERT INTO `his_config_info` VALUES (30, 34, 'provider.yaml', 'PROVIDER_GROUP', '', 'spring:\r\n  datasource:\r\n    username: root\r\n    password: 123456\r\n    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=UTF-8&useSSL=false\r\n    driver-class-name: com.mysql.jdbc.Driver\r\n    type: com.alibaba.druid.pool.DruidDataSource\r\n    druid:\r\n      initial-size: 5       \r\n      min-idle: 5           \r\n      max-active: 20        \r\n      test-on-borrow: true  \r\n      max-wait: 1000        \r\n  \r\n      stat-view-servlet:\r\n        enabled: true\r\n        url-pattern: /druid/*\r\n        login-username: root\r\n        login-password: 123456\r\n      filter:              \r\n        stat:\r\n          log-slow-sql: true\r\n          slow-sql-millis: 1000\r\n          merge-sql: true\r\n        wall:\r\n          config:\r\n            multi-statement-allow: true\r\n  redis:\r\n    host: 127.0.0.1\r\n    port: 6380\r\n    jedis:\r\n      pool:\r\n        max-active: 20\r\n        min-idle: 5\r\n    database: 1\r\n\r\nuseLocalCache: true', 'da92b01f9abf83dcd453d445a807be03', '2010-05-05 00:00:00', '2019-12-26 20:00:31', NULL, '127.0.0.1', 'U', '2572cfa6-38d4-4a72-812b-3347fe50aa98');
INSERT INTO `his_config_info` VALUES (31, 35, 'provider.yaml', 'PROVIDER_GROUP', '', 'spring:\r\n  datasource:\r\n    username: root\r\n    password: 123456\r\n    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=UTF-8&useSSL=false\r\n    driver-class-name: com.mysql.jdbc.Driver\r\n    type: com.alibaba.druid.pool.DruidDataSource\r\n    druid:\r\n      initial-size: 5       \r\n      min-idle: 5           \r\n      max-active: 20        \r\n      test-on-borrow: true  \r\n      max-wait: 1000        \r\n  \r\n      stat-view-servlet:\r\n        enabled: true\r\n        url-pattern: /druid/*\r\n        login-username: root\r\n        login-password: 123456\r\n      filter:              \r\n        stat:\r\n          log-slow-sql: true\r\n          slow-sql-millis: 1000\r\n          merge-sql: true\r\n        wall:\r\n          config:\r\n            multi-statement-allow: true\r\n  redis:\r\n    host: 127.0.0.1\r\n    port: 6380\r\n    jedis:\r\n      pool:\r\n        max-active: 20\r\n        min-idle: 5\r\n    database: 1\r\n\r\nuseLocalCache: true', 'da92b01f9abf83dcd453d445a807be03', '2010-05-05 00:00:00', '2019-12-26 20:00:49', NULL, '127.0.0.1', 'U', '2d5193c9-4b61-453e-8eae-e0fae3b516e1');
INSERT INTO `his_config_info` VALUES (30, 36, 'provider.yaml', 'PROVIDER_GROUP', '', 'spring:\r\n  datasource:\r\n    username: root\r\n    password: 123456\r\n    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=UTF-8&useSSL=false\r\n    driver-class-name: com.mysql.jdbc.Driver\r\n    type: com.alibaba.druid.pool.DruidDataSource\r\n    druid:\r\n      initial-size: 5       \r\n      min-idle: 5           \r\n      max-active: 20        \r\n      test-on-borrow: true  \r\n      max-wait: 1000        \r\n  \r\n      stat-view-servlet:\r\n        enabled: true\r\n        url-pattern: /druid/*\r\n        login-username: root\r\n        login-password: 123456\r\n      filter:              \r\n        stat:\r\n          log-slow-sql: true\r\n          slow-sql-millis: 1000\r\n          merge-sql: true\r\n        wall:\r\n          config:\r\n            multi-statement-allow: true\r\n  redis:\r\n    host: 127.0.0.1\r\n    port: 6380\r\n    jedis:\r\n      pool:\r\n        max-active: 20\r\n        min-idle: 5\r\n    database: 1\r\n\r\nserver:\r\n  port: 8081', '127e42d1a4e6f45cb2a0118124b7b497', '2010-05-05 00:00:00', '2019-12-27 09:12:35', NULL, '127.0.0.1', 'U', '2572cfa6-38d4-4a72-812b-3347fe50aa98');
INSERT INTO `his_config_info` VALUES (30, 37, 'provider.yaml', 'PROVIDER_GROUP', '', 'spring:\r\n  datasource:\r\n    username: root\r\n    password: 123456\r\n    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=UTF-8&useSSL=false\r\n    driver-class-name: com.mysql.jdbc.Driver\r\n    type: com.alibaba.druid.pool.DruidDataSource\r\n    druid:\r\n      initial-size: 5       \r\n      min-idle: 5           \r\n      max-active: 20        \r\n      test-on-borrow: true  \r\n      max-wait: 1000        \r\n  \r\n      stat-view-servlet:\r\n        enabled: true\r\n        url-pattern: /druid/*\r\n        login-username: root\r\n        login-password: 123456\r\n      filter:              \r\n        stat:\r\n          log-slow-sql: true\r\n          slow-sql-millis: 1000\r\n          merge-sql: true\r\n        wall:\r\n          config:\r\n            multi-statement-allow: true\r\n  redis:\r\n    host: 127.0.0.1\r\n    port: 6380\r\n    jedis:\r\n      pool:\r\n        max-active: 20\r\n        min-idle: 5\r\n    database: 1', '96362644a23867f4e7bc4e6cecda01e0', '2010-05-05 00:00:00', '2019-12-27 09:13:00', NULL, '127.0.0.1', 'U', '2572cfa6-38d4-4a72-812b-3347fe50aa98');
INSERT INTO `his_config_info` VALUES (31, 38, 'provider.yaml', 'PROVIDER_GROUP', '', 'spring:\r\n  datasource:\r\n    username: root\r\n    password: 123456\r\n    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=UTF-8&useSSL=false\r\n    driver-class-name: com.mysql.jdbc.Driver\r\n    type: com.alibaba.druid.pool.DruidDataSource\r\n    druid:\r\n      initial-size: 5       \r\n      min-idle: 5           \r\n      max-active: 20        \r\n      test-on-borrow: true  \r\n      max-wait: 1000        \r\n  \r\n      stat-view-servlet:\r\n        enabled: true\r\n        url-pattern: /druid/*\r\n        login-username: root\r\n        login-password: 123456\r\n      filter:              \r\n        stat:\r\n          log-slow-sql: true\r\n          slow-sql-millis: 1000\r\n          merge-sql: true\r\n        wall:\r\n          config:\r\n            multi-statement-allow: true\r\n  redis:\r\n    host: 127.0.0.1\r\n    port: 6380\r\n    jedis:\r\n      pool:\r\n        max-active: 20\r\n        min-idle: 5\r\n    database: 1\r\n\r\nserver:\r\n  port: 8082', '31bc91b899f1c22865b8ff9ef0e878e4', '2010-05-05 00:00:00', '2019-12-27 09:14:03', NULL, '127.0.0.1', 'U', '2d5193c9-4b61-453e-8eae-e0fae3b516e1');

-- ----------------------------
-- Table structure for roles
-- ----------------------------
DROP TABLE IF EXISTS `roles`;
CREATE TABLE `roles`  (
  `username` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `role` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = Dynamic;

-- ----------------------------
-- Records of roles
-- ----------------------------
INSERT INTO `roles` VALUES ('nacos', 'ROLE_ADMIN');

-- ----------------------------
-- Table structure for tenant_capacity
-- ----------------------------
DROP TABLE IF EXISTS `tenant_capacity`;
CREATE TABLE `tenant_capacity`  (
  `id` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `tenant_id` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL DEFAULT '' COMMENT 'Tenant ID',
  `quota` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '配额，0表示使用默认值',
  `usage` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '使用量',
  `max_size` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '单个配置大小上限，单位为字节，0表示使用默认值',
  `max_aggr_count` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '聚合子配置最大个数',
  `max_aggr_size` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '单个聚合数据的子配置大小上限，单位为字节，0表示使用默认值',
  `max_history_count` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '最大变更历史数量',
  `gmt_create` datetime(0) NOT NULL DEFAULT '2010-05-05 00:00:00' COMMENT '创建时间',
  `gmt_modified` datetime(0) NOT NULL DEFAULT '2010-05-05 00:00:00' COMMENT '修改时间',
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE INDEX `uk_tenant_id`(`tenant_id`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 1 CHARACTER SET = utf8 COLLATE = utf8_bin COMMENT = '租户容量信息表' ROW_FORMAT = Dynamic;

-- ----------------------------
-- Table structure for tenant_info
-- ----------------------------
DROP TABLE IF EXISTS `tenant_info`;
CREATE TABLE `tenant_info`  (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'id',
  `kp` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT 'kp',
  `tenant_id` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT '' COMMENT 'tenant_id',
  `tenant_name` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT '' COMMENT 'tenant_name',
  `tenant_desc` varchar(256) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT 'tenant_desc',
  `create_source` varchar(32) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT 'create_source',
  `gmt_create` bigint(20) NOT NULL COMMENT '创建时间',
  `gmt_modified` bigint(20) NOT NULL COMMENT '修改时间',
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE INDEX `uk_tenant_info_kptenantid`(`kp`, `tenant_id`) USING BTREE,
  INDEX `idx_tenant_id`(`tenant_id`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 3 CHARACTER SET = utf8 COLLATE = utf8_bin COMMENT = 'tenant_info' ROW_FORMAT = Dynamic;

-- ----------------------------
-- Records of tenant_info
-- ----------------------------
INSERT INTO `tenant_info` VALUES (1, '1', '2572cfa6-38d4-4a72-812b-3347fe50aa98', 'dev', '开发环境', 'nacos', 1577353474943, 1577353474943);
INSERT INTO `tenant_info` VALUES (2, '1', '2d5193c9-4b61-453e-8eae-e0fae3b516e1', 'test', '测试环境', 'nacos', 1577353492592, 1577353492592);

-- ----------------------------
-- Table structure for users
-- ----------------------------
DROP TABLE IF EXISTS `users`;
CREATE TABLE `users`  (
  `username` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `password` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `enabled` tinyint(1) NOT NULL,
  PRIMARY KEY (`username`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = Dynamic;

-- ----------------------------
-- Records of users
-- ----------------------------
INSERT INTO `users` VALUES ('nacos', '$2a$10$EuWPZHzz32dJN7jexM34MOeYirDdFAZm2kuWj7VEOJhhZkDrxfvUu', 1);

SET FOREIGN_KEY_CHECKS = 1;
